export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGIN_INFO_SAVE = "AUTH_LOGIN_INFO_SAVE";


export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const AUTH_PROFILE_IMG_CHANGE_REQUEST = "AUTH_PROFILE_IMG_CHANGE_REQUEST";
export const AUTH_PROFILE_IMG_CHANGE_SUCCESS = "AUTH_PROFILE_IMG_CHANGE_SUCCESS";

export const POST_PICK = "POST_PICK"
export const POSTER_LOAD_REQUEST = "POSTER_LOAD_REQUEST";
export const POSTER_LOAD_SUCCESS = "POSTER_LOAD_SUCCESS";
export const POSTER_OUTPUT_DATA = "POSTER_OUTPUT_DATA";

//POSTER_MODIFY
export const POSTER_MODIFY_DATA = "POSTER_MODIFY_DATA";

export const HOME_LOAD_REQUEST = "HOME_LOAD_REQUEST";
export const HOME_LOAD_SUCCESS = "HOME_LOAD_SUCCESS";
export const HOME_MORE_REQUEST = "HOME_MORE_REQUEST";
export const HOME_MORE_SUCCESS = "HOME_MORE_SUCCESS";
